spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://localhost:3308/subscription?useSSL=false
    username: subscription
    password: subscription
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update